<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectTypeNameTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            "General Provision",
            "Mangrove Farming",
            "EcoPark",
            "Fishermans Wharf",
            "New technology to aquaculture (e.g. aerator, aquaponics)",
            "Single-Detached Dwelling Unit",
            "Duplex",
            "Single-Detached/Duplex Subdivision",
            "Home Office/Occupation",
            "Home Industry",
            "Recreational Facility",
            "Others",
            "Non-Commercial Uses",
            "Apartment",
            "Boarding House",
            "Dormitories",
            "Museums",
            "Libraries",
            "High School",
            "Vocational School",
            "Drugstore",
            "Residential Condominiums",
            "Townhouses",
            "Pension Houses",
            "Hotel Apartment or Apartelle",
            "Hotels",
            "Motels",
            "Parking within Building",
            "Socialized Housing Provision",
            "Retail Stores and Shops",
            "Food market and shops",
            "Product showroom",
            "Personal Service Shop",
            "Bayad Centers",
            "Laundries",
            "Internet Cafe",
            "Photo/Video/Light/Sounds Services",
            "Catering",
            "Event Planners",
            "Water Stations",
            "Courier Services",
            "Travel Agencies",
            "Photo and Portrait Studios",
            "Repair Shops",
            "Recreational Centers",
            "Mini-Theaters",
            "Video/Karaoke",
            "Electronic Amusement",
            "Restaurants and Eateries",
            "Lotto and Betting Stations",
            "Parks and Playground",
            "Plant Nurseries",
            "Vocational/Technical School",
            "SPED School",
            "Short Term Education",
            "Embassies",
            "Financial Institutions",
            "Offices",
            "Parking Lots/Garage Facilities",
            "Parking Building",
            "Engraving",
            "Electronic Printing/Engraving",
            "Signs Manufacturer",
            "Columbarium",
            "Commercial Housing",
            "Customary Accessories",
            "Wholesale Stores",
            "Wet and Dry Market",
            "Shopping Center/Malls/Supermarket",
            "Bars",
            "Exhibit Halls",
            "Convention Centers",
            "BPO",
            "Radio and TV Stations",
            "Janitorial Services",
            "House furniture and appliances repair shops",
            "Motor vehicles and accessory repair shops",
            "Battery shops and repair shops",
            "Auto repair, tire, vulcanizing shops and car wash",
            "Enclosed Construction supply stores",
            "Funeral parlors",
            "Transportation terminals/ garage with and without repair",
            "Display for cars, tractors, trucks, etc.",
            "Car display and dealer stores",
            "Auto sales and rentals, automotive handicraft, accessory and spare parts shops, marine craft and aircraft sales yards",
            "Boat storage",
            "Vehicle emission testing center",
            "Machinery display shop/ center",
            "Welding shops limited for repair purposes",
            "Machine shop service operation (repairing/ rebuilding or custom job orders)",
            "Glassware and metalware stores, household equipment and appliances",
            "Signboard and streamer painting and silk screening",
            "Electronic printing, copiers and duplicating services",
            "Recording and film laboratories",
            "Paint stores without bulk handling",
            "Gardens and landscaping supply/ contractors",
            "Lechon stores",
            "Other bakery products not elsewhere classified (n.e.c.)",
            "Shops for repacking of food products e.g. fruits, vegetables, sugar and other related products",
            "Funeral parlors (all categories)",
            "Commercial condominium (with residential units in upper floors)",
            "Commercial housing",
            "Regional shopping malls/ centers",
            "High rise hotels and condominium",
            "High rise office buildings",
            "Drying fish",
            "Biscuit factory ? manufacture of biscuits, cookies, crackers and other similar dried bakery products",
            "Doughnut and hopia factory",
            "Manufacture of macaroni, spaghetti, vermicelli and other noodles",
            "Other bakery production not elsewhere classified (n.e.c.)",
            "Life belts factory",
            "Manufacture of luggage, handbags, wallets and small leather goods",
            "Manufacture of miscellaneous products of leather and leather substitute and n.e.c.",
            "Manufacture of shoes except rubber, plastic and wood",
            "Manufacture of slipper and sandal except rubber and plastic",
            "Manufacture of footwear parts except rubber and plastic",
            "Printing, publishing and allied industries and those n.e.c.",
            "Manufacture or assembly of typewriters, cash registers, weighing, duplicating and accounting machines",
            "Manufacture or assembly of electronic data processing machinery and accessories",
            "Renovation and repair of office machinery",
            "Manufacture or assembly of miscellaneous office machines and those n.e.c.",
            "Manufacture of rowboats, bancas and sailboats",
            "Manufacture of animal-drawn vehicles",
            "Manufacture of children vehicles and baby carriages",
            "Manufacture of laboratory and scientific instruments, barometers, chemical balance, etc.",
            "Manufacture of measuring and controlling equipment, plumb bob, rain gauge, taxi meter, thermometer, etc.",
            "Manufacture or assembly of surgical, medical, dental equipment and medical furniture",
            "Popcorn/ rice factory",
            "Manufacture of medical/ surgical supplies, adhesive tapes, antiseptic dressing, sanitary napkins, surgical gauge, etc.",
            "Manufacture of orthopedic and prosthetic appliances (abdominal supporter, ankle supports, arch support, artificial limb, kneecap supporters, etc.)",
            "Manufacture of photographic equipment and accessories",
            "Manufacture or assembly of optical instruments",
            "Manufacture of eyeglasses and spectacles",
            "Manufacture of optical lenses",
            "Manufacture of watches and clocks",
            "Manufacture of pianos",
            "Manufacture of string instruments",
            "Manufacture of wind and percussion instruments",
            "Manufacture or assembly of electronic organs",
            "Manufacture of sporting gloves and mitts",
            "Manufacture of sporting balls (not of rubber or plastic)",
            "Manufacture of gym and playground equipment",
            "Manufacture of sporting tables (billiards, pingpong, pool)",
            "Manufacture of other sporting and athletic goods n.e.c.",
            "Manufacture of toys and dolls except rubber and mold plastic",
            "Manufacture of pens, pencils and other office and artist materials",
            "Manufacture of umbrella and canes",
            "Manufacture of buttons except plastic",
            "Manufacture of brooms, brushes and fans except soaking process",
            "Manufacture of needles, pens, fasteners and zippers",
            "Manufacture of insignia, badges and similar emblems (except metal)",
            "Manufacture of signs and advertising displays (except printed)",
            "Small-scale manufacturing of ice cream",
            "Dairies and creameries",
            "Warehouse/ Storage facility for non-pollutive/ non-hazardous industries",
            "Parks, playgrounds, pocket parks, parkways and promenades",
            "Customary accessory",
            "Manufacture of house furnishing",
            "Textile bag factories",
            "Canvass bags and other canvass products factory",
            "Jute bag factory",
            "Utility installation for use of zone/lot occupants",
            "Inter-modal transport facility",
            "Manufacture or assembly of electronic data processing machinery and accessories",
            "Manufacture of jewelries and fashion accessories",
            "Manufacture of optical lenses",
            "Manufacture of miscellaneous textile goods, embroideries and weaving apparel",
            "Manufacture of fiber batting, padding and upholstery filling except coir",
            "Men?s and boys? garment factory",
            "Women?s and girls? and ladies? garments factory",
            "Manufacture of hats, gloves, handkerchief, neckwear and related clothing accessories",
            "Manufacture of raincoats and waterproof outer garments except jackets",
            "Manufacture of miscellaneous wearing apparel except footwear",
            "Commercial housing (e.g. hotels and condominiums), groceries and convenience stores, provided that such will be constructed on existing residential areas prior to the effectivity of this Ordinance.",
            "And other high-value consumer-oriented products which involves non-hazardous and non-pollutive activities.",
            "Parks, pocket parks, parkway, promenade, playground, playlots, sports field/court, garden",
            "Hotels, condominiums",
            "Malls, department stores",
            "Groceries and convenience stores",
            "Recreational center",
            "Bars, sing-along lounges, bistros, pubs, beer gardens, disco, dance halls",
            "Exhibit halls",
            "Office",
            "Bank, ATM, finance, insurance, money exchange service, pawnshop, one-stop payment center",
            "Library, museum, exhibit area, art gallery",
            "College/university, cultural/educational center",
            "Medical center",
            "Specialty school/training facility",
            "Computer/information technology-related service activity",
            "Dining facilities",
            "Parking structure",
            "Organic farm and hydroponic facility",
            "Columbarium",
            "5-star resort hotels",
            "Condominium",
            "Traveler?s lounge",
            "Stadium, arenas",
            "Theme parks",
            "Boardwalks/promenades",
            "Factory outlet centers",
            "Water-oriented recreation/ sports rental equipment shops",
            "Tourism-oriented retail shops (e.g. souvenirs, clothes, etc.)",
            "MARINA facilities",
            "Foreign exchange shops/establishments",
            "Embassy",
            "General/specialized hospital, medical center",
            "Parks, pocket parks, parkway, playground, playlots, sports field/court, garden",
            "Manufacture of designer furniture",
            "Manufacture of prefabricated housing and accessory",
            "Manufacture of trailer home",
            "Assembly of office, accounting, computing machinery and other computer hardware (e.g. Desktop PCs/Laptops, Printers, Keyboards)",
            "Assembly of General-purpose machinery (e.g. Air or vacuum pumps; air or other gas compressors, Pumps for liquids, escalators and moving walkways, air conditioning machines)",
            "Assembly of Electrical machinery and apparatus (e.g. AC/DC motor, automatic circuit breakers, optical fiber cables, Indicator panels incorporating liquid crystal devices (LCD) or light emitting diodes (LED), Electric burglar or fire alarms and similar apparatus)",
            "Assembly of radio, television and communication equipment and apparatus",
            "Assembly of transport equipment (e.g. Parts and accessories of motor vehicles, bicycles and other cycles, not motorized, Boat parts and other accessories)",
            "Manufacture of engines and turbines",
            "Factories for engines and turbines and attached testing facilities",
            "Manufacture of fabricated structural iron and steel",
            "Manufacture of architectural and ornamental metal works",
            "Manufacture of stamped coated and engraved metal products",
            "Manufacture of fabricated wire and cable products",
            "Manufacture of other fabricated metal products except machinery and equipment n.e.c.",
            "Manufacture or assembly of service industry machines",
            "Manufacture or assembly of elevators and escalators",
            "Refrigeration industry",
            "Manufacture or assembly of electrical apparatus",
            "Manufacture or assembly of electrical cables and wires",
            "Manufacture of other electrical industrial machinery and apparatus n.e.c.",
            "Manufacture or assembly of electric equipment ? radio, television, tape recorder, stereo",
            "Manufacture or assembly of radio and television transmitting, signaling and detection equipment",
            "Manufacture or assembly of telephone and telegraphic equipment",
            "Manufacture of other electronic equipment and apparatus n.e.c.",
            "Manufacture of industrial and commercial electrical appliances",
            "Textile and fiber spinning mills",
            "Manufacture of perfumes, cosmetics and other toilet preparations",
            "Tire retreating and rebuilding",
            "Manufacture of pottery, china and earthen ware n.e.c.",
            "Manufacture of flat glass",
            "Manufacture of glass containers",
            "Manufacture of miscellaneous glass and glass products n.e.c.",
            "Manufacture of locomotives and parts",
            "Manufacture or assembly of automobiles, cars, buses, trucks and trailers",
            "Pension houses, Apartel",
            "Shop houses",
            "Novelty shops, souvenir shops, antique/vintage shops, toy shops, fashion accessory shops, cosmetic shops",
            "Alfresco cafes, coffee/tea house,",
            "Restaurants and food strip",
            "Mini movie theater",
            "Billiard halls, pool rooms and bowling alleys",
            "Furniture display shops",
            "Trade and Financial Center",
            "MICE (Meetings, Incentives, Conventions and Exhibits)",
            "High-end Manufacturing Design and Creative Hub",
            "Manufacture of miscellaneous fabricated mill work and those n.e.c.",
            "Manufacture of wooden and cane containers",
            "Sawali, nipa and split cane factory",
            "Manufacture of bamboo, rattan and other cane baskets and wares",
            "Manufacture of cork products",
            "Manufacture of wooden shoes, shoe lace and other similar products",
            "Manufacture of miscellaneous wood products and those n.e.c.",
            "Manufacture of miscellaneous furniture and fixture except primarily of metals and those n.e.c.",
            "Manufacture of paper stationery, envelopes and related articles",
            "Warehouse/ Storage Facility for non-pollutive/ hazardous industries",
            "Parks, playgrounds, pocket parks, parkways and promenades",
            "Customary accessory",
            "Manufacturing and canning of ham, bacon and native sausage",
            "Poultry processing and canning",
            "Large-scale manufacturing of ice cream",
            "Ice plants and cold storage buildings",
            "Manufacture of ice, ice blocks, cubes, tubes, crush except dry ice",
            "Quick freezing and cold packaging for fish and other seafoods",
            "Quick freezing and cold packaging for fruits and vegetables",
            "Corn mill/ rice mill",
            "Chocolate and cocoa factory",
            "Candy factory",
            "Chewing gum factory",
            "Peanuts and other nuts factory",
            "Other chocolate and confectionery products",
            "Manufacturing of flavoring extracts",
            "Manufacture of food products n.e.c. (vinegar, vetsin)",
            "Manufacture of fish meal",
            "Oyster shell grading",
            "Manufacture of medicinal and pharmaceutical preparations",
            "Manufacture of stationery, art goods, cut stone and marble products",
            "Manufacture of abrasive products",
            "Manufacture of miscellaneous non-metallic mineral products n.e.c.",
            "Manufacture of cutlery, except table flatware",
            "Manufacture of hand tools",
            "Manufacture of general hardware",
            "Manufacture of miscellaneous cutlery hand tools and general hardware n.e.c.",
            "Manufacture of household metal furniture",
            "Manufacture of office, store and restaurant metal furniture",
            "Manufacture of metal blinds, screens and shades",
            "Manufacture of miscellaneous furniture and fixture primarily of metal n.e.c.",
            "Manufacture of boilers, tanks and other structural sheet metal works",
            "Manufacture of other structural products n.e.c.",
            "Manufacture of metal cans, boxes and containers",
            "Manufacture of heating, cooking and lighting equipment except electrical",
            "Sheet metal works generally manual operation",
            "Manufacture or assembly of agricultural machinery and equipment",
            "Native plow and harrow factory",
            "Repair of agricultural machinery",
            "Manufacture or assembly of sewing machines",
            "Manufacture or assembly of cooking ranges",
            "Manufacture or assembly of water pumps",
            "Manufacture or assembly of other machinery and equipment except electrical n.e.c.",
            "Manufacture of household cooking, heating and laundry appliances",
            "Manufacture of other electrical appliances n.e.c.",
            "Manufacture of electric lamp fixtures",
            "Warehouse/ Storage Facility for pollutive/ non-hazardous",
            "Flour mill",
            "Cassava flour mill",
            "Manufacture of coffee",
            "Manufacturing of unprepared animal feeds, other grain milling n.e.c.",
            "Production prepared feeds for animals",
            "Grains and cement silos",
            "Cigar and cigarette factory",
            "Curing and re-drying tobacco leaves",
            "Miscellaneous processing tobacco leaves n.e.c.",
            "Textile and fiber spinning mills",
            "Weaving hemp textile",
            "Jute spinning and weaving",
            "Miscellaneous spinning and weaving mills n.e.c.",
            "Hosiery mill",
            "Underwear and outwear knitting mills",
            "Garment and undergarment factories",
            "Fabric knitting mills",
            "Miscellaneous knitting mills n.e.c.",
            "Manufacture of mats and mattings",
            "Manufacture of carpets and rugs",
            "Manufacture of cordage, rope and twine",
            "Manufacture of related products from abaca, sisal, henequen, hemp, cotton, paper, etc.",
            "Manufacture of linoleum and other surface coverings",
            "Manufacture of artificial leather, oil cloth and other fabrics except rubberized",
            "Manufacture of coir",
            "Manufacture of miscellaneous textile n.e.c.",
            "Manufacture of rough lumber, unworked",
            "Manufacture of worked lumber",
            "Re-sawmills",
            "Woodworking establishments, lumber and timber yards",
            "Planning mills and sawmills, veneer plants",
            "Manufacture of veneer, plywood and hardwood",
            "Manufacture of doors, windows and sashes",
            "Treating and preserving of wood",
            "Wood drying kilns",
            "Manufacture of charcoal",
            "Manufacture of wood and cane blinds, screens and shades",
            "Pulp, paper and paperboard factories",
            "Manufacture of containers and boxes of paper and paper boards",
            "Wood and cardboard box factories",
            "Manufacture of miscellaneous pulp and paper products n.e.c.",
            "Manufacture of perfumes, cosmetics and other toilet preparations",
            "Manufacture of waxes and polishing preparations",
            "Manufacture of candles",
            "Manufacture of inks",
            "Repackaging of industrial products e.g. paints, varnishes and other related products",
            "Manufacture of miscellaneous chemical products n.e.c.",
            "Manufacture of rubber shoes and slippers",
            "Manufacture of industrial and molded rubber products",
            "Manufacture of plastic footwear",
            "Manufacture of plastic furniture",
            "Manufacture of other fabricated plastic products n.e.c.",
            "Manufacture of table and kitchen articles",
            "Manufacture of miscellaneous glass and glass products n.e.c.",
            "Manufacture of clay bricks, clay tiles and hollow clay tiles",
            "Manufacture of miscellaneous structural clay products n.e.c",
            "Manufacture of structural concrete products",
            "Manufacture of asbestos products",
            "Manufacture of engines and turbines except motor vehicles, marine and aircraft",
            "Manufacture of metal cutting, shaving and finishing machinery",
            "Manufacture of wood working machinery",
            "Manufacture, assembly, rebuilding, repairing of food and beverage making machinery",
            "Manufacture, assembly, rebuilding, repairing of textile machinery and equipment",
            "Manufacture, assembly, rebuilding, repairing of paper industry machinery",
            "Manufacture, assembly, rebuilding, repairing of trade machinery and equipment",
            "Manufacture of rice mills",
            "Manufacture of machines for leather and leather products",
            "Manufacture of construction machinery",
            "Manufacture of machines for clay, stove and glass industries",
            "Manufacture, assembly, repair and rebuilding of miscellaneous special industrial machinery and equipment n.e.c.",
            "Manufacture of dry cells, storage battery and other batteries",
            "Boat building and repairing",
            "Ship repairing industry, dock yards, dry dock, shipways",
            "Miscellaneous shipbuilding and repairing n.e.c.",
            "Manufacture of locomotives and parts",
            "Manufacture of railroad and street cars",
            "Hangars",
            "Manufacture and assembly plants of aircraft engine",
            "Repair and testing shops for aircraft engines and parts",
            "Manufacture of wood furniture including upholstery",
            "Manufacture of rattan furniture including upholstery",
            "Manufacture of box beds and mattresses",
            "Dry cleaning plants using flammable liquids",
            "Paint stores with bulk handling",
            "Paint shops and spray painting rooms",
            "Signs and billboards painting shops",
            "Warehouses where highly combustible materials are stored",
            "Factories where loose combustible fiber or dirt are manufactured, processed or generated",
            "Warehouse for pollutive/ hazardous",
            "Government or civic centers to house national, regional or local offices in the area",
            "Police and fire stations",
            "Other types of government buildings",
            "Colleges, universities, professional business schools, vocational and trade schools, technical schools and other institutions of higher learning",
            "Learning facilities such as training centers, seminar halls and libraries",
            "Scientific, cultural and academic centers and research facilities except nuclear, radioactive, chemical and biological warfare facilities",
            "Museums, exhibition halls and art galleries",
            "Convention center and related facilities",
            "Civic centers and community centers",
            "General hospitals, medical centers, specialty hospitals, medical, dental and similar clinics,",
            "Welfare home, orphanages, boys and girls town, nursing homes, homes for the aged and the like",
            "Rehabilitation and vocational training centers for ex-convicts, drug addicts, unwed mothers, physically, mentally and emotionally handicapped, ex-sanitaria inmates and similar establishments",
            "Leprosaria",
            "Psychiatric facilities, such as mental hospitals, mental sanitaria/ asylums",
            "Places of worship, such as churches, mosques, temples, shrines, chapels",
            "Seminaries and convents",
            "Embassies/ consulates",
            "Military camps/ reservations/ bases and training grounds",
            "Jails, prisons, reformatories and correctional institution",
            "Penitentiaries and correctional institutions",
            "Parking buildings",
            "Parks, playgrounds, pocket parks, parkways, promenades and playlots",
            "Parks, playgrounds, pocket parks, parkways, promenades and playlots, gardens",
            "All types of resort complexes such as those providing accommodation, sports, dining and other leisure facilities",
            "Open air or outdoor sports activities and support facilities, including low rise stadia, gyms, amphitheaters and swimming pools",
            "Ball courts, skating rinks and similar uses",
            "Memorial/ Shrines monuments, kiosks and other park structures",
            "Sports clubs",
            "Open space buffers and easements",
            "Memorial Parks",
            "Cemetery",
            "Crematorium",
            "Ossuary",
            "Open spaces/gardens",
            "Parks and park structures such as playgrounds, jogging trails, bicycle lanes",
            "Plant nurseries",
            "Ground-level or underground parking structures/ facilities",
            "Agriculture, silviculture, horticulture",
            "Power plants (thermal, hydro, geothermal, wind, solar)",
            "Pumping plants [water supply, storm drainage, sewerage, irrigation and waste treatment plants]",
            "Liquid and solid waste management facilities",
            "Climate monitoring facilities",
            "Telecommunication facilities such as cell (mobile) phone towers",
            "All other types of large complexes for public services",
            "Government facility",
            "Public utility facility",
            "Hotel, condominiums",
            "Convention, meetings facility",
            "Auditorium, theater, performance, civic center (not commercial cinema)",
            "Show rooms",
            "Factory outlet center",
            "Office",
            "Radio or television station",
            "Parking structure",
            "Place of religious worship"
        ];

        for ($i=0; $i < count($data); $i++) {
            DB::table('project_type_name')->insert([
                    'name' => $data[$i]
            ]);
        }
    }
}
